export default {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  PRECONDITION_REQUIRED: 'PRECONDITION_REQUIRED',
  AUTH: {
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  },
  USER: {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    INVALID_ID: 'INVALID_ID',
    INVALID_USERNAME: 'INVALID_USERNAME',
  },
};
